database:
  type: postgresql
spring:
  profiles:
    active: postgresql
  data:
    mongodb:
      uri: mongodb://localhost:27017/data_tracker
      #username: myusername
      #password: mypassword
  application:
    name: pay-tracker
  datasource:
    #url: jdbc:postgresql://10.6.22.201:6010/payment_action
    #username: admin_role
    #password: @dm1n_r0le@2023
    url: jdbc:postgresql://localhost:5432/data_tracker?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     # ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_schema: action_tracker
    show_sql: true
    open-in-view: false
  server:
    port: 9090
    servlet:
      context-path: /payTracker
